name: at_hive_recovery
description: A command-line utility to recover corrupt hive box
version: 1.0.1
publish_to: none

executables:
  at_hive_recovery: main

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  at_persistence_secondary_server: ^3.0.5
  crypto: ^3.0.1

dependency_overrides:
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: packages/at_persistence_secondary_server
      ref: dart-3


dev_dependencies:
  lints: ^1.0.1
