name: at_dump_atKeys
description: A command-line utility to dump keys from an atKeys file
version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependency_overrides:
  at_pkam:
    path: ../at_pkam
dependencies:
  crypton: ^2.0.1
  encrypt: ^5.0.0
  archive: ^3.1.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.5
