name: at_repl
description: A command line tool that interacts with the at_platform.
version: 1.0.0
repository: https://github.com/atsign-foundation/at_tools
environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.1
  at_client: ^3.0.59
  at_onboarding_cli: ^1.3.0
  at_utils: ^3.0.12
  io: ^1.0.4
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_verify: ^3.1.0

executables:
  at_repl: at_repl
