name: at_repl
description: A command line tool that interacts with the at_platform.
version: 1.0.1
repository: https://github.com/atsign-foundation/at_tools
environment:
  sdk: ^3.0.0

executables:
  at_repl: at_repl

dependencies:
  args: ^2.4.1
  at_client: ^3.0.61
  at_commons: ^3.0.47
  at_onboarding_cli: ^1.3.0
  at_utils: ^3.0.12
  io: ^1.0.4
  build_version: ^2.1.1
  build_runner: ^2.4.5
  pub_updater: ^0.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

