name: at_pkam
description: A command-line utility to generate PKAM digest
version: 1.1.0+1
# homepage: https://www.example.com

executables:
  at_pkam: main

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypton: ^2.0.1
  encrypt: ^5.0.0
  archive: ^3.1.2

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.5
