name: at_ve_doctor
description: A sample command-line application.
publish_to: none
version: 1.1.1
# homepage: https://www.example.com

executables:
  at_ve_doctor: at_ve_doctor

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  at_server_status: ^1.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.14.4
