import 'dart:io';

import 'package:at_onboarding_cli/at_onboarding_cli.dart';
import 'package:sshnp_register_tool/io_util.dart';

class OnboardingUtil {
  /// Creates ~/.atsign/keys/ directory if it doesn't exist already
  /// Uses at_onboarding_cli to onboard given the atSign (e.g. '@bob'), rootUrl ('root.atsign.org:64') and the cramkey generated by the API (e.g. 'MIljujdkljasdlk3j21...')
  static Future<bool> onboard(
      String atSign, String rootUrl, String cram) async {
    final Uri uriDir = Uri.directory(
        '${Platform.environment['HOME']}/.atsign/keys/',
        windows: Platform.isWindows);
    final Directory dir = Directory.fromUri(uriDir);
    final String path = dir.path;

    await IOUtil.createDir(path);

    final List<String> s = rootUrl.split(":");
    final AtOnboardingPreference pref = AtOnboardingPreference()
      ..cramSecret = cram
      ..downloadPath = path
      ..rootDomain = s[0]
      ..rootPort = int.parse(s[1]);

    final AtOnboardingService service = AtOnboardingServiceImpl(atSign, pref);

    final bool onboarded = await service.onboard();
    service.close();
    return onboarded;
  }
}
